export const SHIBAS_GET_SHIBAS_REQUEST = 'SHIBAS_GET_SHIBAS_REQUEST';
export const SHIBAS_GET_SHIBAS_SUCCESS = 'SHIBAS_GET_SHIBAS_SUCCESS';
export const SHIBAS_GET_SHIBAS_FAILURE = 'SHIBAS_GET_SHIBAS_FAILURE';

export const SHIBAS_SWIPE_RIGHT_SHIBA_REQUEST = 'SHIBAS_SWIPE_RIGHT_SHIBA_REQUEST';
export const SHIBAS_SWIPE_RIGHT_SHIBA_SUCCESS = 'SHIBAS_SWIPE_RIGHT_SHIBA_SUCCESS';
export const SHIBAS_SWIPE_RIGHT_SHIBA_FAILURE = 'SHIBAS_SWIPE_RIGHT_SHIBA_FAILURE';

export const SHIBAS_SWIPE_LEFT_SHIBA_REQUEST = 'SHIBAS_SWIPE_LEFT_SHIBA_REQUEST';
export const SHIBAS_SWIPE_LEFT_SHIBA_SUCCESS = 'SHIBAS_SWIPE_LEFT_SHIBA_SUCCESS';
export const SHIBAS_SWIPE_LEFT_SHIBA_FAILURE = 'SHIBAS_SWIPE_LEFT_SHIBA_FAILURE';

export const SHIBAS_TOGGLE_MATCH_MODAL = 'SHIBAS_TOGGLE_MATCH_MODAL';